//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRecord
    {
        public int GameRecordId { get; set; }
        public System.DateTime RecordTime { get; set; }
        public int Column { get; set; }
        public Nullable<int> GameId { get; set; }
        public string UserName { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
